name = "jiwonz/luau_regexp"
version = "0.1.3"
description = "[Fork] A regular expression library for Luau. Uploaded for pesde"
authors = ["Roblox", "Blockzez", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/luau-regexp"
license = "MIT"
includes = ["README.md", "pesde.toml", "src/**", "LICENSE"]
private = true

[target]
environment = "luau"
lib = "src/Regexp_global.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.8.9"
pesde = "^0.6.0"

[dev_dependencies]
multitarget = { name = "jiwonz/multitarget", version = "^0.4.0-rc.29", target = "lune" }
