name = "jiwonz/luau_regexp"
version = "0.1.2"
description = "A regular expression library for Luau. Uploaded for pesde"
authors = ["Roblox", "Blockzez", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/luau-regexp"
license = "MIT"
includes = ["README.md", "pesde.toml", "src/**", "LICENSE"]

[target]
environment = "luau"
lib = "src/Regexp.global.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[engines]
lune = "^0.8.9"
pesde = "^0.6.0"
