std = "luau"

[config.empty_if]
comments_count = true

[config.global_usage]
ignore_pattern = "LUA_ENV"

[config.shadowing]
ignore_pattern = "result|ok|^_"

[config.unused_variable]
ignore_pattern = "result|ok|^_"

[rules]
global_usage = "allow"
if_same_then_else = "allow"
shadowing = "allow"
unused_variable = "allow"
mixed_table = "allow"
empty_if = "allow"
